### ISSUE TITLE
&, < 등에 \ 기호 적절히 붙지 않음 현상관련 질문

### ISSUE THREAD

**Issue by nicepig7** [nhn/to-mark#44]
혹시 정규식의 [] 앞뒤로 \\ 붙이신 것은 의도한 기능인가요?

https://github.com/nhn/to-mark/blob/c942d85b88f52ff38b206e4eeefb262dcabc42f9/src/renderer.js#L408

**Comment by seonim-ryu** [comment]
@nicepig7 
The regular expression seems to be related to [this issue](https://github.com/nhn/to-mark/commit/ea296911f852c7884edb9cfe11bec7d301e1c651). By the way, what do you mean the backslash(`\`) doesn't append properly? Can you explain in more detail?

**Comment by nicepig7** [comment]
코드 작성의 의도를 잘 몰라 드린 질문인지는 모르겠습니다.
아래 예시는 Chrome(console)에서 테스트 한 결과입니다.
```
markdownTextToEscapeBackSlashRx = /.../;
var a = /\\[!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~\\]/;
console.log(a.test("!"), false);
console.log(a.test("\\[!\"#$%&'()*+,-./:;<=>?@[\]^_`{|}~\\]"), true);

var b = /[!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~]/;
console.log(b.test("!"), true);
```
추측컨데  b를 의도한 것으로 예상했습니다만
만약 a가 원래 의도한 것이라면 대다수의 경우에서는 test가 통과 되지 않을것으로 생각됩니다.

**Comment by nicepig7** [comment]
제가 정규식 테스트를 잘못했었습니다.
해당 건은 closed 시키겠습니다. (_ _)
