### ISSUE TITLE
Why the horizontal line use "- - -" instead of "---"

### ISSUE THREAD

**Issue by kelvinkoko** [nhn/to-mark#45]
Just curious the decision choice of horizontal line here
https://github.com/nhn/to-mark/blob/master/src/renderer.basic.js#L219

I agree "- - -" is acceptable syntax but just look like "---" is more common

**Comment by seonim-ryu** [comment]
@kelvinkoko 
I don't know the exact history of why `- - -` was used. But it's not a problem because the syntax doesn't violate [CommonMark specification](https://spec.commonmark.org/0.29/#example-21). Why did you ask this?

**Comment by kelvinkoko** [comment]
@seonim-ryu Thanks for your reply. Yes, i agree it is correct and not a bug. Just my other lib fail to recognise "- - -" I understand that It is their fault and not "to-mark" fault :) But just make me curious why chose to use this style.

**Comment by seonim-ryu** [comment]
@kelvinkoko 
I don't know which library you're using, but they might not have considered the specs. Anyway, the issue seems to be resolved, so I'll close it :)
